import type { Application } from "@/lib/types";

export const SEED: Application[] = [
  {
    id: "seed-1",
    company: "Vercel",
    role: "Senior Frontend Engineer",
    status: "Interview",
    location: "Remote — US",
    remote: true,
    source: "Referral",
    appliedDate: new Date(Date.now() - 14 * 864e5).toISOString(),
    salaryMin: 180000,
    salaryMax: 220000,
    notes: "Referred by Priya. Recruiter screen went well; next is system design.",
    link: "https://vercel.com/careers",
    jobUrl: "https://vercel.com/careers",
    logoColor: "#6366f1",
    priority: true,
    nextAction: "Prep system design round",
    timeline: [
      { label: "Saved", date: new Date(Date.now() - 15 * 864e5).toISOString(), done: true },
      { label: "Applied", date: new Date(Date.now() - 14 * 864e5).toISOString(), done: true },
      { label: "Recruiter Screen", date: new Date(Date.now() - 7 * 864e5).toISOString(), done: true },
      { label: "Technical Interview", date: new Date(Date.now() - 2 * 864e5).toISOString(), done: true },
      { label: "Final Interview", date: "", done: false },
      { label: "Offer", date: "", done: false },
    ],
    events: [
      { id: "e1", date: new Date(Date.now() - 14 * 864e5).toISOString(), text: "Applied via referral", type: "applied" },
      { id: "e2", date: new Date(Date.now() - 7 * 864e5).toISOString(), text: "Recruiter screen — positive", type: "screen" },
      { id: "e3", date: new Date(Date.now() - 2 * 864e5).toISOString(), text: "Technical round passed", type: "interview" },
    ],
    interviews: [
      {
        id: "iv1",
        date: new Date(Date.now() + 3 * 864e5).toISOString(),
        type: "Technical",
        withWhom: "Engineering manager",
        completed: false,
        focus: "System design, rendering strategies",
      },
    ],
  },
  {
    id: "seed-2",
    company: "Linear",
    role: "Product Engineer",
    status: "Applied",
    location: "Remote",
    remote: true,
    source: "Company site",
    appliedDate: new Date(Date.now() - 5 * 864e5).toISOString(),
    salaryMin: 150000,
    salaryMax: 190000,
    notes: "Love their craft quality. Mentioned the changelog redesign in cover letter.",
    link: "https://linear.app/careers",
    jobUrl: "https://linear.app/careers",
    logoColor: "#5e6ad2",
    nextAction: "Follow up if no reply by day 7",
    timeline: [
      { label: "Saved", date: new Date(Date.now() - 6 * 864e5).toISOString(), done: true },
      { label: "Applied", date: new Date(Date.now() - 5 * 864e5).toISOString(), done: true },
      { label: "Recruiter Screen", date: "", done: false },
      { label: "Technical Interview", date: "", done: false },
      { label: "Final Interview", date: "", done: false },
      { label: "Offer", date: "", done: false },
    ],
    events: [
      { id: "e4", date: new Date(Date.now() - 5 * 864e5).toISOString(), text: "Applied on company site", type: "applied" },
    ],
    interviews: [],
  },
  {
    id: "seed-3",
    company: "Stripe",
    role: "Full-stack Engineer, Payments",
    status: "Offer",
    location: "San Francisco / Hybrid",
    remote: false,
    source: "LinkedIn",
    appliedDate: new Date(Date.now() - 40 * 864e5).toISOString(),
    salaryMin: 200000,
    salaryMax: 260000,
    notes: "Offer in hand. Negotiating base — they have room per levels.fyi data.",
    link: "https://stripe.com/jobs",
    jobUrl: "https://stripe.com/jobs",
    logoColor: "#635bff",
    priority: true,
    nextAction: "Respond to offer by Friday",
    timeline: [
      { label: "Saved", date: new Date(Date.now() - 41 * 864e5).toISOString(), done: true },
      { label: "Applied", date: new Date(Date.now() - 40 * 864e5).toISOString(), done: true },
      { label: "Recruiter Screen", date: new Date(Date.now() - 30 * 864e5).toISOString(), done: true },
      { label: "Technical Interview", date: new Date(Date.now() - 20 * 864e5).toISOString(), done: true },
      { label: "Final Interview", date: new Date(Date.now() - 10 * 864e5).toISOString(), done: true },
      { label: "Offer", date: new Date(Date.now() - 3 * 864e5).toISOString(), done: true },
    ],
    events: [
      { id: "e5", date: new Date(Date.now() - 40 * 864e5).toISOString(), text: "Applied via LinkedIn", type: "applied" },
      { id: "e6", date: new Date(Date.now() - 10 * 864e5).toISOString(), text: "Final round complete", type: "interview" },
      { id: "e7", date: new Date(Date.now() - 3 * 864e5).toISOString(), text: "🎁 Offer received!", type: "offer" },
    ],
    interviews: [],
  },
  {
    id: "seed-4",
    company: "Notion",
    role: "Frontend Engineer, Editor",
    status: "Rejected",
    location: "San Francisco",
    remote: false,
    source: "AngelList",
    appliedDate: new Date(Date.now() - 25 * 864e5).toISOString(),
    salaryMin: 150000,
    salaryMax: 200000,
    notes: "Rejected after phone screen — weak on collaborative editing internals. Study CRDTs.",
    logoColor: "#ef4444",
    timeline: [
      { label: "Saved", date: new Date(Date.now() - 26 * 864e5).toISOString(), done: true },
      { label: "Applied", date: new Date(Date.now() - 25 * 864e5).toISOString(), done: true },
      { label: "Recruiter Screen", date: new Date(Date.now() - 18 * 864e5).toISOString(), done: true },
      { label: "Technical Interview", date: "", done: false },
      { label: "Final Interview", date: "", done: false },
      { label: "Offer", date: "", done: false },
    ],
    events: [
      { id: "e8", date: new Date(Date.now() - 25 * 864e5).toISOString(), text: "Applied", type: "applied" },
      { id: "e9", date: new Date(Date.now() - 18 * 864e5).toISOString(), text: "Phone screen — didn't advance", type: "rejection" },
    ],
    interviews: [],
  },
  {
    id: "seed-5",
    company: "Anthropic",
    role: "Software Engineer, UI",
    status: "Screening",
    location: "San Francisco",
    remote: false,
    source: "Company site",
    appliedDate: new Date(Date.now() - 3 * 864e5).toISOString(),
    salaryMin: 220000,
    salaryMax: 300000,
    notes: "Recruiter reaching out next week. Review Claude API + tooling familiarity.",
    logoColor: "#d97757",
    nextAction: "Confirm recruiter call time",
    timeline: [
      { label: "Saved", date: new Date(Date.now() - 4 * 864e5).toISOString(), done: true },
      { label: "Applied", date: new Date(Date.now() - 3 * 864e5).toISOString(), done: true },
      { label: "Recruiter Screen", date: "", done: false },
      { label: "Technical Interview", date: "", done: false },
      { label: "Final Interview", date: "", done: false },
      { label: "Offer", date: "", done: false },
    ],
    events: [
      { id: "e10", date: new Date(Date.now() - 3 * 864e5).toISOString(), text: "Applied on company site", type: "applied" },
    ],
    interviews: [
      {
        id: "iv2",
        date: new Date(Date.now() + 6 * 864e5).toISOString(),
        type: "Behavioral",
        withWhom: "Recruiter (30 min)",
        completed: false,
        focus: "Background, motivation, logistics",
      },
    ],
  },
];
