import type { Application } from "./types";

const t = (daysAgo: number) => new Date(Date.now() - daysAgo * 86400000).toISOString();

// helper to build a timeline relative to appliedDate
function tl(appliedDaysAgo: number, stages: number[]): { date: string; label: string; done: boolean }[] {
  const labels = ["Saved", "Applied", "Recruiter Screen", "Technical Interview", "Final Interview", "Offer"];
  return labels.map((label, i) => {
    const d = stages[i];
    return { label, date: d != null ? t(appliedDaysAgo - d) : "", done: d != null };
  });
}

export const MOCK_APPLICATIONS: Application[] = [
  {
    id: "a1",
    company: "Vercel",
    logoColor: "#000000",
    role: "Senior Frontend Engineer",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 180000,
    salaryMax: 240000,
    appliedDate: t(12),
    status: "Interview",
    jobUrl: "https://vercel.com/careers",
    recruiter: { name: "Sarah Kim", email: "sarah.k@vercel.com" },
    notes: "Loved the take-home. Mentioned Next.js middleware work in my cover letter.",
    nextAction: "Prep for system design round",
    description: "Join the DX team building the Next.js developer experience. You'll own critical paths in the dashboard and edge tooling.",
    timeline: tl(12, [1, 0, 5, 9]),
    interviews: [
      { date: t(7), type: "Recruiter Screen", withWhom: "Sarah Kim", completed: true },
      { date: t(2), type: "Technical Interview", withWhom: "Tobias Lütke panel", completed: true },
      { date: t(-3), type: "System Design", withWhom: "Engineering Manager", completed: false, focus: "Edge runtime and caching architecture" },
    ],
  },
  {
    id: "a2",
    company: "Linear",
    logoColor: "#5E6AD2",
    role: "Product Engineer",
    location: "Remote (US)",
    remote: true,
    salaryMin: 160000,
    salaryMax: 210000,
    appliedDate: t(20),
    status: "Offer",
    jobUrl: "https://linear.app/careers",
    recruiter: { name: "Jane Manchun", email: "jane@linear.app" },
    notes: "Verbal offer received — negotiating on equity.",
    nextAction: "Respond to offer by Friday",
    description: "Build the fastest issue tracker ever made. Small team, huge craft bar, React + TypeScript everywhere.",
    timeline: tl(20, [2, 0, 6, 12, 17]),
    interviews: [
      { date: t(14), type: "Recruiter Screen", withWhom: "Jane", completed: true },
      { date: t(8), type: "Technical", withWhom: "Tuomas", completed: true },
      { date: t(3), type: "Final", withWhom: "Karri Saarinen", completed: true },
    ],
  },
  {
    id: "a3",
    company: "Stripe",
    logoColor: "#635BFF",
    role: "Backend Engineer, Payments",
    location: "Seattle, WA",
    remote: false,
    salaryMin: 190000,
    salaryMax: 260000,
    appliedDate: t(30),
    status: "Rejected",
    jobUrl: "https://stripe.com/jobs",
    notes: "Rejected after technical. They said strong fundamentals but needed more distributed systems depth.",
    nextAction: "",
    description: "Work on the money movement engine processing billions daily.",
    timeline: tl(30, [1, 0, 8, 21]),
    interviews: [
      { date: t(22), type: "Recruiter Screen", withWhom: "Stripe Recruiting", completed: true },
      { date: t(9), type: "Technical", withWhom: "Payments team", completed: true },
    ],
  },
  {
    id: "a4",
    company: "Anthropic",
    logoColor: "#D97757",
    role: "Full-Stack Engineer, Console",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 200000,
    salaryMax: 280000,
    appliedDate: t(8),
    status: "Screening",
    jobUrl: "https://anthropic.com/careers",
    recruiter: { name: "Priya Nair", email: "priya@anthropic.com" },
    notes: "Recruiter reached out on LinkedIn first. Very responsive.",
    nextAction: "Send portfolio link",
    description: "Build developer-facing tooling for the Claude API console.",
    timeline: tl(8, [0, 1, 4]),
    interviews: [
      { date: t(4), type: "Intro Call", withWhom: "Priya Nair", completed: true },
      { date: t(-3), type: "Screening", withWhom: "Console Engineering Lead", completed: false, focus: "React, streaming responses, API architecture" },
    ],
  },
  {
    id: "a5",
    company: "Notion",
    logoColor: "#37352F",
    role: "Frontend Engineer, Blocks",
    location: "New York, NY",
    remote: true,
    salaryMin: 150000,
    salaryMax: 200000,
    appliedDate: t(15),
    status: "Interview",
    jobUrl: "https://notion.so/careers",
    notes: "The editor rendering challenge was fun. They use a custom CRDT layer.",
    nextAction: "Follow up after onsite",
    description: "Own performance and correctness of the block editing experience used by millions.",
    timeline: tl(15, [1, 0, 6, 11]),
    interviews: [
      { date: t(9), type: "Recruiter Screen", withWhom: "Notion Talent", completed: true },
      { date: t(3), type: "Technical", withWhom: "Editor team", completed: true },
    ],
  },
  {
    id: "a6",
    company: "Raycast",
    logoColor: "#FF6363",
    role: "Desktop Engineer (Electron)",
    location: "Remote (Europe)",
    remote: true,
    salaryMin: 120000,
    salaryMax: 160000,
    appliedDate: t(5),
    status: "Applied",
    jobUrl: "https://raycast.com/careers",
    notes: "Referred by @thomaspaulmann on Twitter.",
    nextAction: "Wait for response",
    description: "Build the future of the Raycast desktop app. Build Electron-native UX primitives and the extension API.",
    timeline: tl(5, [0, 1]),
    interviews: [],
  },
  {
    id: "a7",
    company: "Supabase",
    logoColor: "#3ECF8E",
    role: "Developer Experience Engineer",
    location: "Remote (Global)",
    remote: true,
    salaryMin: 140000,
    salaryMax: 185000,
    appliedDate: t(25),
    status: "Rejected",
    jobUrl: "https://supabase.com/careers",
    notes: "They paused hiring for this req. Told me to reapply in Q4.",
    nextAction: "Set reminder to reapply in October",
    description: "Improve the developer experience of the open-source Firebase alternative.",
    timeline: tl(25, [1, 0]),
    interviews: [],
  },
  {
    id: "a8",
    company: "Figma",
    logoColor: "#F24E1E",
    role: "Product Engineer, Design Systems",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 185000,
    salaryMax: 250000,
    appliedDate: t(18),
    status: "Final Round",
    jobUrl: "https://figma.com/careers",
    recruiter: { name: "Marcus Webb", email: "marcus@figma.com" },
    notes: "Onsite went really well. Loved the panel. Fingers crossed.",
    nextAction: "Send thank-you notes",
    description: "Ship user-facing features across Figma's collaborative canvas.",
    timeline: tl(18, [2, 0, 7, 13, 16]),
    interviews: [
      { date: t(11), type: "Recruiter Screen", withWhom: "Marcus Webb", completed: true },
      { date: t(6), type: "Technical", withWhom: "App team", completed: true },
      { date: t(2), type: "Final Onsite", withWhom: "Panel of 4", completed: true },
    ],
  },
  {
    id: "a9",
    company: "GitHub",
    logoColor: "#24292F",
    role: "Senior Software Engineer, Copilot",
    location: "Remote (US)",
    remote: true,
    salaryMin: 190000,
    salaryMax: 250000,
    appliedDate: t(40),
    status: "Rejected",
    jobUrl: "https://github.careers",
    notes: "Ghosted after screening, then got auto-rejection 3 weeks later.",
    nextAction: "",
    description: "Work on AI-assisted developer tooling at planetary scale.",
    timeline: tl(40, [1, 0, 10]),
    interviews: [
      { date: t(30), type: "Recruiter Screen", withWhom: "GitHub Talent", completed: true },
    ],
  },
  {
    id: "a10",
    company: "Airbnb",
    logoColor: "#FF5A5F",
    role: "Frontend Engineer, Hosting",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 175000,
    salaryMax: 230000,
    appliedDate: t(10),
    status: "Screening",
    jobUrl: "https://careers.airbnb.com",
    recruiter: { name: "Elena Rodriguez", email: "elena.r@airbnb.com" },
    notes: "Recruiter call scheduled. They emphasize design taste heavily.",
    nextAction: "Prep examples of design-driven work",
    description: "Build the hosting experience used by millions of hosts worldwide.",
    timeline: tl(10, [0, 1]),
    interviews: [
      { date: t(-2), type: "Recruiter Screen", withWhom: "Elena Rodriguez", completed: false, focus: "Portfolio and design systems" },
    ],
  },
  {
    id: "a11",
    company: "Datadog",
    logoColor: "#632CA6",
    role: "Software Engineer, Tracing",
    location: "New York, NY",
    remote: true,
    salaryMin: 165000,
    salaryMax: 215000,
    appliedDate: t(22),
    status: "Screening",
    jobUrl: "https://datadoghq.com/careers",
    notes: "Coding screen next week. Rust + Go for the agent.",
    nextAction: "Practice Rust coding challenges",
    description: "Build distributed tracing pipelines ingesting trillions of spans.",
    timeline: tl(22, [1, 0, 3]),
    interviews: [
      { date: t(-4), type: "Online Assessment", withWhom: "HackerRank", completed: false, focus: "Concurrency and systems programming" },
    ],
  },
  {
    id: "a12",
    company: "Shopify",
    logoColor: "#95BF47",
    role: "Senior Frontend Developer",
    location: "Remote (Canada)",
    remote: true,
    salaryMin: 155000,
    salaryMax: 200000,
    appliedDate: t(28),
    status: "Interview",
    jobUrl: "https://shopify.com/careers",
    recruiter: { name: "Devon Lane", email: "devon.l@shopify.com" },
    notes: "Life story interview was surprisingly intense. Technical upcoming.",
    nextAction: "Prep for pair-programming session",
    description: "Build merchant-facing admin surfaces with React and GraphQL.",
    timeline: tl(28, [2, 0, 10, 20]),
    interviews: [
      { date: t(18), type: "Life Story", withWhom: "Hiring Manager", completed: true },
      { date: t(-5), type: "Pair Programming", withWhom: "Checkout team", completed: false, focus: "GraphQL and performance optimization" },
    ],
  },
  {
    id: "a13",
    company: "Cloudflare",
    logoColor: "#F38020",
    role: "Systems Engineer, Workers",
    location: "Austin, TX",
    remote: true,
    salaryMin: 180000,
    salaryMax: 240000,
    appliedDate: t(35),
    status: "Applied",
    jobUrl: "https://cloudflare.com/careers",
    notes: "Applied via referral from college on the Workers team.",
    nextAction: "Nudge referral contact",
    description: "Push the boundaries of serverless compute at the edge.",
    timeline: tl(35, [1, 0]),
    interviews: [],
  },
  {
    id: "a14",
    company: "Ramp",
    logoColor: "#E9004C",
    role: "Full-Stack Engineer, Finance Ops",
    location: "New York, NY",
    remote: true,
    salaryMin: 170000,
    salaryMax: 225000,
    appliedDate: t(6),
    status: "Applied",
    jobUrl: "https://ramp.com/careers",
    notes: "Their careers page says response within 5 days. Day 6 now.",
    nextAction: "Follow up on application",
    description: "Automate corporate finance workflows end to end.",
    timeline: tl(6, [0, 1]),
    interviews: [],
  },
  {
    id: "a15",
    company: "Retool",
    logoColor: "#3D3D3D",
    role: "Frontend Engineer, Editor",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 175000,
    salaryMax: 220000,
    appliedDate: t(3),
    status: "Saved",
    jobUrl: "https://retool.com/careers",
    notes: "Saw the role on Hacker News. Applying this weekend.",
    nextAction: "Tailor resume for editor perf work",
    description: "Build the drag-and-drop app editor used by half of the Fortune 500.",
    timeline: tl(3, [0]),
    interviews: [],
  },
  {
    id: "a16",
    company: "OpenAI",
    logoColor: "#10A37F",
    role: "Member of Technical Staff, Platform",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 250000,
    salaryMax: 350000,
    appliedDate: t(14),
    status: "Interview",
    jobUrl: "https://openai.com/careers",
    recruiter: { name: "Alex Chen", email: "alexc@openai.com" },
    notes: "Fastest-moving process I've ever seen. Two rounds in one week.",
    nextAction: "Deep dive on distributed training infra",
    description: "Build and scale the infrastructure behind frontier models.",
    timeline: tl(14, [1, 0, 4, 9]),
    interviews: [
      { date: t(10), type: "Recruiter Screen", withWhom: "Alex Chen", completed: true },
      { date: t(4), type: "Technical Deep Dive", withWhom: "Platform team", completed: true },
    ],
  },
  {
    id: "a17",
    company: "Docker",
    logoColor: "#2496ED",
    role: "Senior Frontend Engineer",
    location: "Palo Alto, CA",
    remote: true,
    salaryMin: 160000,
    salaryMax: 200000,
    appliedDate: t(45),
    status: "Rejected",
    jobUrl: "https://docker.com/careers",
    notes: "Went with a candidate who had Kubernetes internals experience.",
    nextAction: "",
    description: "Shape the developer experience of container tooling.",
    timeline: tl(45, [1, 0, 12]),
    interviews: [
      { date: t(33), type: "Recruiter Screen", withWhom: "Docker Recruiting", completed: true },
    ],
  },
  {
    id: "a18",
    company: "Tailscale",
    logoColor: "#4B70CC",
    role: "Software Engineer, Client",
    location: "Remote (US/Canada)",
    remote: true,
    salaryMin: 150000,
    salaryMax: 190000,
    appliedDate: t(9),
    status: "Applied",
    jobUrl: "https://tailscale.com/careers",
    notes: "Small team, very writing-heavy culture. Sent a writing sample.",
    nextAction: "Wait for response",
    description: "Make zero-config a reality with WireGuard.",
    timeline: tl(9, [1, 0]),
    interviews: [],
  },
  {
    id: "a19",
    company: "Framer",
    logoColor: "#0055FF",
    role: "Design Engineer",
    location: "Amsterdam (Remote)",
    remote: true,
    salaryMin: 90000,
    salaryMax: 130000,
    appliedDate: t(16),
    status: "Screening",
    jobUrl: "https://framer.com/careers",
    notes: "They asked for a portfolio of interactions. Sent the spring-physics demo.",
    nextAction: "Prepare live coding of Framer Motion work",
    description: "Blur the line between design and code on the web.",
    timeline: tl(16, [1, 0, 5]),
    interviews: [
      { date: t(2), type: "Portfolio Review", withWhom: "Design lead", completed: true },
    ],
  },
  {
    id: "a20",
    company: "Coinbase",
    logoColor: "#0052FF",
    role: "Software Engineer, Consumer",
    location: "Remote (US)",
    remote: true,
    salaryMin: 175000,
    salaryMax: 235000,
    appliedDate: t(33),
    status: "Rejected",
    jobUrl: "https://coinbase.com/careers",
    notes: "Level mismatch — they wanted more crypto-native experience.",
    nextAction: "",
    description: "Build the main app used by 100M+ people to interact with crypto.",
    timeline: tl(33, [1, 0]),
    interviews: [],
  },
  {
    id: "a21",
    company: "Plaid",
    logoColor: "#111111",
    role: "Product Engineer, Transactions",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 185000,
    salaryMax: 240000,
    appliedDate: t(11),
    status: "Interview",
    jobUrl: "https://plaid.com/careers",
    recruiter: { name: "Nina Patel", email: "nina.p@plaid.com" },
    notes: "Take-home is a transactions enrichment API. Due Thursday.",
    nextAction: "Submit take-home project",
    description: "Power the fintech ecosystem by connecting apps to bank data.",
    timeline: tl(11, [1, 0, 5, 8]),
    interviews: [
      { date: t(6), type: "Recruiter Screen", withWhom: "Nina Patel", completed: true },
    ],
  },
  {
    id: "a22",
    company: "Cal.com",
    logoColor: "#292929",
    role: "Full-Stack Engineer (Open Source)",
    location: "Remote (Global)",
    remote: true,
    salaryMin: 110000,
    salaryMax: 150000,
    appliedDate: t(2),
    status: "Saved",
    jobUrl: "https://cal.com/careers",
    notes: "Open-source-first. Might contribute a PR first to stand out.",
    nextAction: "Find a good-first-issue on the repo",
    description: "Build the open-source scheduling infrastructure alternative to Calendly.",
    timeline: tl(2, [0]),
    interviews: [],
  },
  {
    id: "a23",
    company: "Netlify",
    logoColor: "#05BDBA",
    role: "Senior Engineer, DX",
    location: "Remote (US/EU)",
    remote: true,
    salaryMin: 165000,
    salaryMax: 210000,
    appliedDate: t(26),
    status: "Screening",
    jobUrl: "https://netlify.com/careers",
    notes: "Hiring manager liked my blog post on edge rendering.",
    nextAction: "Send follow-up with edge demo repo",
    description: "Improve the build and deploy experience of the modern web.",
    timeline: tl(26, [2, 0, 6]),
    interviews: [
      { date: t(3), type: "Hiring Manager Screen", withWhom: "DX Lead", completed: true },
    ],
  },
  {
    id: "a24",
    company: "Loom",
    logoColor: "#625DF5",
    role: "Frontend Engineer, Player",
    location: "New York, NY",
    remote: true,
    salaryMin: 150000,
    salaryMax: 195000,
    appliedDate: t(50),
    status: "Rejected",
    jobUrl: "https://loom.com/careers",
    notes: "Position was filled internally. They encouraged me for future roles.",
    nextAction: "",
    description: "Craft the async video player and editor experience.",
    timeline: tl(50, [1, 0]),
    interviews: [],
  },
  {
    id: "a25",
    company: "Warp",
    logoColor: "#00E599",
    role: "Founding Engineer",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 160000,
    salaryMax: 220000,
    appliedDate: t(7),
    status: "Applied",
    jobUrl: "https://warp.dev/careers",
    notes: "Rust-heavy role. Mentioned my terminal emulation side project.",
    nextAction: "Polish terminal side-project repo",
    description: "Reinvent the terminal with modern UX and AI.",
    timeline: tl(7, [0, 1]),
    interviews: [],
  },
  {
    id: "a26",
    company: "Zed",
    logoColor: "#084CCF",
    role: "Software Engineer, Collaboration",
    location: "Remote (US)",
    remote: true,
    salaryMin: 170000,
    salaryMax: 230000,
    appliedDate: t(1),
    status: "Saved",
    jobUrl: "https://zed.dev/careers",
    notes: "Prefer Rust experience. Watched their collab architecture talk.",
    nextAction: "Finish Rust CLI project",
    description: "Build real-time collaboration for the fastest code editor.",
    timeline: tl(1, [0]),
    interviews: [],
  },
  {
    id: "a27",
    company: "Rippling",
    logoColor: "#2B2E85",
    role: "Senior Full-Stack Engineer",
    location: "San Francisco, CA",
    remote: true,
    salaryMin: 175000,
    salaryMax: 225000,
    appliedDate: t(24),
    status: "Screening",
    jobUrl: "https://rippling.com/careers",
    recruiter: { name: "Chris Ford", email: "chris.f@rippling.com" },
    notes: "OA completed, awaiting results.",
    nextAction: "Check OA results portal",
    description: "Unify HR, IT, and finance in one employee management platform.",
    timeline: tl(24, [1, 0, 8]),
    interviews: [
      { date: t(13), type: "Online Assessment", withWhom: "CodeSignal", completed: true },
    ],
  },
  {
    id: "a28",
    company: "Brex",
    logoColor: "#F46A35",
    role: "Frontend Engineer, Dashboard",
    location: "Remote (US)",
    remote: true,
    salaryMin: 170000,
    salaryMax: 220000,
    appliedDate: t(19),
    status: "Applied",
    jobUrl: "https://brex.com/careers",
    notes: "Heard the team ships fast. WPM (what problem do you want to solve) essay submitted.",
    nextAction: "Wait for response",
    description: "Redefine financial software for growing companies.",
    timeline: tl(19, [1, 0]),
    interviews: [],
  },
  {
    id: "a29",
    company: "Scale AI",
    logoColor: "#151515",
    role: "Software Engineer, Tooling",
    location: "San Francisco, CA",
    remote: false,
    salaryMin: 180000,
    salaryMax: 240000,
    appliedDate: t(42),
    status: "Rejected",
    jobUrl: "https://scale.com/careers",
    notes: "Went with a candidate who had Kubernetes internals experience.",
    nextAction: "",
    description: "Build internal tools powering data labeling for frontier AI labs.",
    timeline: tl(42, [1, 0, 14]),
    interviews: [
      { date: t(28), type: "Recruiter Screen", withWhom: "Scale Recruiting", completed: true },
    ],
  },
  {
    id: "a30",
    company: "Expo",
    logoColor: "#000020",
    role: "Open Source Engineer",
    location: "Remote (Global)",
    remote: true,
    salaryMin: 130000,
    salaryMax: 175000,
    appliedDate: t(13),
    status: "Applied",
    jobUrl: "https://expo.dev/careers",
    notes: "Contributed 3 PRs to expo-cli before applying. Hiring manager recognized my username!",
    nextAction: "Wait for triage of latest PR",
    description: "Advance the React Native ecosystem and developer tooling.",
    timeline: tl(13, [1, 0]),
    interviews: [],
  },
  {
    id: "a31",
    company: "Gusto",
    logoColor: "#F45D48",
    role: "Senior Software Engineer, Payroll",
    location: "Denver, CO",
    remote: true,
    salaryMin: 165000,
    salaryMax: 205000,
    appliedDate: t(31),
    status: "Screening",
    jobUrl: "https://gusto.com/careers",
    recruiter: { name: "Hannah Lee", email: "hannah.l@gusto.com" },
    notes: "Recruiter screen went well. They care a lot about mission alignment.",
    nextAction: "Read up on payroll compliance basics",
    description: "Build payroll systems that millions of small businesses rely on.",
    timeline: tl(31, [2, 0, 9]),
    interviews: [
      { date: t(22), type: "Recruiter Screen", withWhom: "Hannah Lee", completed: true },
    ],
  },
  {
    id: "a32",
    company: "PostHog",
    logoColor: "#F54E00",
    role: "Full-Stack Engineer, Product",
    location: "Remote (Global)",
    remote: true,
    salaryMin: 140000,
    salaryMax: 190000,
    appliedDate: t(4),
    status: "Screening",
    jobUrl: "https://posthog.com/careers",
    notes: "Their handbook is public and incredibly detailed. Small team, ship daily.",
    nextAction: "Read handbook sections on hiring",
    description: "Build the single platform for product analytics, feature flags and more.",
    timeline: tl(4, [1, 0, 2]),
    interviews: [
      { date: t(-1), type: "Intro Chat", withWhom: "Charles Delingpole", completed: false, focus: "Product thinking & open-source" },
    ],
  },
  {
    id: "a33",
    company: "Arc Browser",
    logoColor: "#767676",
    role: "Software Engineer, Core Experience",
    location: "New York, NY",
    remote: false,
    salaryMin: 155000,
    salaryMax: 200000,
    appliedDate: t(21),
    status: "Applied",
    jobUrl: "https://arc.net/careers",
    notes: "They said review on a rolling basis. The Browser Company UI kit is a marvel.",
    nextAction: "Wait for response",
    description: "Reinvent the web browser from first principles.",
    timeline: tl(21, [1, 0]),
    interviews: [],
  },
  {
    id: "a34",
    company: "Neon",
    logoColor: "#00E599",
    role: "Developer Experience Engineer",
    location: "Remote (EU/US)",
    remote: true,
    salaryMin: 145000,
    salaryMax: 185000,
    appliedDate: t(17),
    status: "Interview",
    jobUrl: "https://neon.tech/careers",
    recruiter: { name: "Sofia Martins", email: "sofia@neon.tech" },
    notes: "Loved the serverless Postgres deep dive. Next is a DX-focused exercise.",
    nextAction: "Build the DX exercise demo",
    description: "Build the developer experience layer of serverless Postgres.",
    timeline: tl(17, [1, 0, 6, 12]),
    interviews: [
      { date: t(11), type: "Recruiter Screen", withWhom: "Sofia Martins", completed: true },
      { date: t(5), type: "Technical Chat", withWhom: "DX team", completed: true },
    ],
  },
];
